### ISSUE TITLE
中间的get和set是基于什么考虑呢？

### ISSUE THREAD

**Issue by xbpk3t** [xiaozhi805157387/RandUserData#1]
后面的几个rand方法直接返回变量就可以了吧，个人感觉不需要set之后再get出来吧...

**Comment by xiaozhi805157387** [comment]
对的， 估计是一下子手快set也弄出来了

**Comment by xiaozhi805157387** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
